= CSC8104: Enterprise Distributed Computing Coursework [TODO: new title], November 2013

== Outline
This coursework is designed to give you experience with building Java EE 6 applications and deploying them to the Cloud. In part one you will build a service with a web front end, hosted on a Platform as a Service Cloud. In part two you will create a more complex service by orchestrating your colleagues' services into a bigger application.

You must complete the provided Tutorial before attempting this coursework. There are a number of prerequisite steps in the tutorial that must be done for the coursework to work.

== Technologies
This coursework covers a large number of technologies. The challenge here is to learn the right bits of each technology in order to complete the coursework.

* Angular.js. This is the technology you will use for the web-interface to your application.
* Java EE 6. Java Enterprise Edition is the technology you will use to develop the server-side part of your application.
* JPA. Java Persistence API provides a Java API onto your application's data.
* Bean Validation. This technology allows you to specify constraints on your data and assists with validation.
* Arquillian. With this tool you will be able to write tests that run inside the application server.
* Maven. Your application will be built and deployed with this tool.
* EJB Session beans. TODO 
* Openshift. This is the Platform as a Service (PaaS) that you will use to deploy your application to the Cloud.
* REST. This technology will be used for communication between your web interface (running in the web browser) and your service (running in the Cloud).
* Git. This is a distributed version control sytem and will be used to backup your code and for deploying it to OpenShift.

== Project Specification

IMPORTANT: You must write all the elements of the coursework yourself. You must NOT use tools/wizards (such as Eclipse) to write them for you! However, you are encouraged to use Eclipse as your IDE. 

For this project you must create a Maven build for your application. You must also produce Arquillian tests for testing your application; these tests must also run from Maven. At the end of the project you will submit to NESS a zip file containing the source code and Maven build scripts. We will use this zip file to test your submission, so it should contain everything necessary to build and test your project. 

TIP: You will be awarded a considerable number of marks for your distribution and use use of version controll.

TODO: explain how to use GitHub repo.

== General Processs
TODO: build on kitchensink, don't worry about renaming packages, OpenShift application, etc. Regular commits. develop locally and push to OpenShift when working.

== Part 1 

Produce a web site selling ONE of the services from the following list. Your website *must* be developed using HTML5 and Angular.js technologies. You should now be familiar with these technologies after completing the provided tutorial.

* Taxi 
* Flight 
* Hotel 

IMPORTANT: You have been allocated a service to implement. See the allocation list in the tutorial document for details. You MUST implement the service that you have been allocated. 

The following diagram shows the architecture you will need to implement for your application:

[TODO: insert architecture diagram]

* Web-site. This is implemented with HTML5 and Angular.js. The code here is responsible for providing the user-interface and runs entirely in the user's web browser. It communicates with your server in the Cloud (or locally during development) when invoking operations, such as making a booking or listing users. This is done using...
* REST Services. These are implemented using JAX-RS and provide a service interface to your application. These services are responsible for managing bookings, users and taxis/hotels/flights. 
* Persistence layer. This layer provides a Java interface for accessing the data in the database, using the Java Persistence API (JPA).
* Database. This is where your data is stored. Your application won't access this directly as it will use JPA to interface with the data. 


=== Web-site
Your web-site should provide an interface to:

1. Create & List customers
2. Create & List items (taxis, rooms or flights)
3. Create, Cancel & list bookings

IMPORTANT: You will be marked purely on how well your site works. No marks will be given for how the site looks.

=== REST Services
You will need three REST services:

1. Customer. Lists and creates customers.
2. Taxi/Hotel/Flight. Lists and creates items.
3. Booking. Creates and cancels bookings.

=== Persistence Layer
You will probably need three Entity Beans.

1. Customer. A bean to hold the data you wish to collect about each customer.
2. Taxi/Flight/Hotel. A bean to hold the data you wish to collect about each item you have available for booking.
3. Booking. A bean representing the booking and linking to the customer who made the booking and to the item being booked.

TIP: Keep these entities simple. Just provide the minimum information required to fullfil the requirements. 

=== Report Hints
* Describe the composition of your service, including each of the JAX-RS services and how they interact. You might like to draw a diagram like the one above to help explain your architecture.

== Part 2
You will now need to integrate three services into a simple travel agent application; which you will update your web site to support. You will use your own service and two other services provided by your colleagues.
The services you need to integrate are: 

* 1 x Hotel service 
* 1 x Taxi services 
* 1 x Flight service 

You must ensure that either every part of a booking is made, or no parts of the booking are made. Remember, each part of the booking can be cancelled using the provided cancel operation. For example, the user would not want to book a flight, if they didn't have somewhere to stay at the destination.
You should provide a mechanism that allows a booking to fail. For example, you could fail a booking if the date is too far in the future. This will allow you to easily control which booking fails and which succeeds. You should then be able to set up a scenario where the first two bookings succeed and the remaining booking fails. Your web application should detect this failure and cancel the previous bookings that succeeded.

IMPORTANT: It is very important that the user does not end up with a partial booking. Otherwise they may end up paying for a flight, without having a hotel to stay in.

[TODO: insert diagram here]
 
The diagram above shows the type of interaction that you should have achieved by completing part 2.

TIP: You may find that you are ready to use your colleagues’ services before they are ready to make them available. If this happens then you can temporarily use your own service three times and then switch to your colleagues’ services when they become available.

TIP: You may also find it hard to utilize the exact service types specified above, due to the progress of your colleagues. In this case you may duplicate the service types; for example, two Taxi services and one Flight service. However, you must make sure that the two services you select are offered by two different colleagues!

=== Report Hints
* What problems did you have utilising your colleagues’ services? How would these problems be exacerbated had the producers of these services not been in the same room?
* What problems did you have offering your service to your colleagues?

=== Part 3
TODO

== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do. 

You must be able to demonstrate each part of this project to the Course Demonstrators. Then the code must be submitted via the coursework submission system (NESS). As stated above, we must be able to build and test your submission using your Maven build. 

Also submit a short report via NESS (roughly two pages) summarising the work you carried out on this project, and your assessment of how much you managed to achieve. We have provided a list of things you should cover in your report in the "Report Hints" sections of this document.


