= CSC8104 Introduction

The module learning outcomes, and intended skill outcomes can be found on the link:https://www.ncl.ac.uk/postgraduate/degrees/module/?code=CSC8104[Enterprise Software and Services page].

To complete this coursework you *MUST* first complete the tutorial document and then move onto the coursework document.

== Tutorial

Follow https://github.com/NewcastleComputingScience/CSC8104-Quarkus-Specification/blob/main/tutorial.asciidoc[this document]

You may also https://www.youtube.com/watch?v=2SkR8hDCpvA[watch this video] to see the steps in action.

Many steps of the tutorial and video concern the environment setup necessary to undertake the coursework on your own machines. This year much of this setup has been performed for you on university machines.
If you are solely using a university machine to perform the coursework, you should complete only the subsections of the https://github.com/NewcastleComputingScience/CSC8104-Quarkus-Specification/blob/main/tutorial.asciidoc[tutorial] which are highlighted as necessary for *all students*.

IMPORTANT: Immediately after you create your GitHub account and Red Hat Developers account, email Adam Booth at (a.booth2@ncl.ac.uk) with your name, email address, GitHub username and Red Hat Login ID.
Adam will then create your private repository. You will then receive an email informing you of the details once everything is ready.


== Coursework

Follow https://github.com/NewcastleComputingScience/CSC8104-Quarkus-Specification/blob/main/coursework.asciidoc[this document].

IMPORTANT: You must use the allocation list below to determine which service type you will implement.


== Course Teacher Profiles

*Module (Course) Leader*: *Dr Ellis Solaiman* is the Enterprise Software and Services module (course) leader, and also leads a number of courses at the school of Computing Science, Newcastle University including the MSc final Project and Dissertation. He obtained his PhD in Computing Science from Newcastle University in 2004. His research interests are related mainly to the management of distributed systems (Cloud and IoT), trust, and Computer Science Education.

*Lead Demonstrator:* *Adam Booth* is a final year PhD student with the Centre for Doctoral Training in Geospatial Systems and is currently researching the application of machine learning and blockchain technologies to geospatial systems. Adam has studied at Newcastle University, undertaking CSC8104 as a postgraduate student. He is currently the head demonstrator on the Enterprise Software and Services course.

*Demonstrator:* *Kobby Adu-Duodu* is a third year year PhD student at the School of Computing, Newcastle Univeristy. His research interests lie in the development of ontology and Blockchain solutions within Circular Supply Chains. 

*Demonstrator:* *Maryam Mosleh* is a first year PhD student and PGTA (Post Graduate Teaching Assistant) at the School of Computing, Newcastle Univeristy. 

*Demonstrator:* *Xinyuan Liu* is a 3rd year PhD student in Computer Science at Newcastle University, UK. 

*Industry (Red Hat) Lead:* *Dr Adam Cattermole* is a Software Engineer at Red Hat. Prior to this role, Adam Completed a PhD at Newcastle University School of Computing where he was also lead demonstrator on the Enterprise Software and Services module. 

*Industry (Red Hat) Lead:* *Dr Paul Robinson* is a Software Engineering Manager at Red Hat and manages the Engineering team for Red Hat's Developer Program. Prior to this role, Paul was a Principal Software Engineer on JBoss EAP working on the Transaction Manager service. Paul is also a Visiting Fellow at the University. Paul has lead the Enterprise Software and Services coursework for over 10 years.

== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do.

Discussion Boards will also be available for CSC8104 in Canvas (http://canvas.ncl.ac.uk) and Teams. You may post any questions about the tutorial or coursework assignment here, and the discussion boards will be monitored by Course Demonstrators. Also, any question which demonstrators encounter frequently (either on Blackboard or in practical) will be placed in a *Frequently Asked Questions* document which we maintain https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc[here]. Before asking a question we encourage you to check both these places to see if it has already been answered.

In particular, notice the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc#i-cant-work-out-how-to-do-[answer] which refers to documentation. The use of 3rd party documentation is absolutely *essential* throughout this coursework, and demonstrators may often answer questions by pointing you to the relevant websites.

TIP: If you see a question on the discussion boards you know how to answer, we strongly encourage you to assist your colleagues!


== Allocation List

[options="header"]
|=====
| Student Name | Service Type | Service Location
| Alden P.A |Flight| 
| Mashael A.A. Alqsayer |Taxi| 
| Pandurang Arun Vajramatti |Hotel|
| Vipul S. Bagal |Flight| 
| Siddhant Bhasin |Taxi| 
| SHANTANU R. CHAUDHARY |Hotel|
| Ben Clough |Flight|
| Swapnil Dalavi |Taxi|
| Xiangtian Deng |Hotel|
| Chhagan S. Gavit |Flight|
| Weihan Hu |Taxi|
| Karthick Keeranagere Krishnaiah |Hotel|
| Animesh Kumar |Flight|
| Mayank S. Kunwar |Taxi| https://csc-8104-mayank-kunwar-crt-9690097516-dev.apps.rm3.7wse.p1.openshiftapps.com/q/swagger-ui/
| Aaditya A. Kute |Hotel|
| Haodong Li |Flight| 
| VARSHA MAHADEVAPPA |Taxi| 
| Bhushan S. Mali |Hotel|
| Siddhesh Mishra |Flight| 
| Kaylum F. Moir |Taxi| 
| Ho Y. MONG |Hotel|
| Aniket V. Nalawade |Flight|
| Suhas S. Nale |Taxi| 
| Paritosh P. Pal |Hotel|
| Rishabh V. Patle |Flight| 
| Syed M. Raheeb |Taxi|
| Manish D. Rane |Hotel|
| Matthew Rollings |Flight| 
| Shivani A. Salunkhe |Taxi|  
| Mingyuan SHAO |Hotel| 
| KHWAJA N. SHOUKATH BASHEER |Flight| 
| DEEPAL S. THAKUR |Taxi| 
| Neha Thipperudrappa |Hotel|
| Jack M. Towler |Flight|
| Chaithanya Virupaksha |Taxi|
| Ewan Walker |Hotel|
| Jason Walker |Flight| 
| Zhenpeng Xie |Taxi|
| Vinit V. Yewale | Hotel |
| Qianqian Zhang | Flight |
|=======



IMPORTANT: If your name does not appear in the allocation list please contact Adam Booth at a.booth2@newcastle.ac.uk as soon as possible (prior to the first practical session) and you will be assigned a service type and a private GitHub repository.
