= CSC8104 Introduction

The module learning outcomes, and intended skill outcomes can be found on the link:http://www.ncl.ac.uk/undergraduate/modules/csc8104/[Enterprise Middleware page].

To complete this coursework you *MUST* first complete the tutorial document and then move onto the coursework document.

== Tutorial

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[this document]

You may also https://youtu.be/YK_YZNBz97A[watch this video], prepared for last year's tutorial, to see the steps in action.

Many steps of the tutorial and video concern the environment setup necessary to undertake the coursework on your own machines. This year much of this setup has been performed for you on university machines.
If you are solely using a university machine to perform the coursework, you should complete only the subsections of the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[tutorial] which are highlighted as necessary for *all students*.

IMPORTANT: Immediately after you create your Github account, send your registration email to Adam Cattermole at (a.cattermole@ncl.ac.uk), including your name and university email address.
If you already have an account, email Adam Cattermole at (a.cattermole@ncl.ac.uk) with your name, email address and Github username.
Adam will then create your private repository and grant you access. You will then receive an email notification from Github containing details of your new repository.
This will be sent to the email address you registered with Github.


== Coursework

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/coursework.asciidoc[this document].

IMPORTANT: You must use the allocation list below to determine which service type you will implement.


== Course Teacher Profiles

*Module (Course) Leader*: *Dr Ellis Solaiman* is the Enterprise Middleware module (course) leader, and also leads a number of courses at the school of Computing Science, Newcastle University including the MSc final Project and Dissertation. He obtained his PhD in Computing Science from Newcastle University in 2004. His research interests are related mainly to the management of distributed systems (Cloud and IoT), trust, and Computer Science Education.

*Industry (Red Hat) Lead:* *Dr Paul Robinson* is a Principal Software Engineer at Red Hat and Leads the JBoss Developer team who provide Red Hat's Middleware developer programme. Paul is also a Visiting Fellow at the University. Paul has lead the Enterprise Middleware coursework for over 10 years. He also supervises students for their Masters dissertation through industrial placements at Red Hat.

*Head Demonstrator:* *Adam Cattermole* is a first year PhD student with the Centre for Doctoral Training in Cloud Computing for Big Data and is currently researching functional stream processing. Adam has studied at Newcastle University since 2012, undertaking CSC8104 as an undergraduate. He is currently the head demonstrator on the Enterprise Middleware course.

*Demonstrator:* *Saleh Mohamed* is a third year PhD student with the Centre for Doctoral Training in Cloud Computing for Big Data and is currently researching on distributed run-time infrastructure for Internet of Things (IoT). He previously received his MSc in Computer Science (Cloud Computing) from Newcastle University.

*Demonstrator* *Yinhao Li* is a second year PhD student in the scalable computing group. His research interests are Internet of Things (IoT), Cloud Computing and Edge Computing. He previously received his MSc in Computer Science from the China University of Geoscience.

// *Demonstrator:* *Devki Jha*

// *Demonstrator:* *Pedro Pinto Da Silva*

// *Demonstrator:* *George Stamatiadis*

== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do.

Discussion Boards will also be available for CSC8104 in Blackboard (http://bb.ncl.ac.uk). You may post any questions about the tutorial or coursework assignment here, and the discussion boards will be monitored by Course Demonstrators. Also, any question which demonstrators encounter frequently (either on Blackboard or in practical) will be placed in a *Frequently Asked Questions* document which we maintain https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc[here]. Before asking a question we encourage you to check both these places to see if it has already been answered.

In particular, notice the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc#i-cant-work-out-how-to-do-[answer] which refers to documentation. The use of 3rd party documentation is absolutely *essential* throughout this coursework, and demonstrators may often answer questions by pointing you to the relevant websites.

TIP: If you see a question on the discussion boards you know how to answer, we strongly encourage you to assist your colleagues!


== Allocation List

[options="header"]
|=====
| Student name | Service Number | Service
|=======

IMPORTANT: If your name does not appear in the allocation list please contact Adam Cattermole at a.cattermole@newcastle.ac.uk as soon as possible (prior to the first practical session) and you will be assigned a service type and a private GitHub repository.
