= CSC8104 Introduction

The module learning outcomes, and intended skill outcomes can be found on the link:http://www.ncl.ac.uk/undergraduate/modules/csc8104/[Enterprise Middleware page].

To complete this coursework you *MUST* first complete the tutorial document and then move onto the coursework document.

== Tutorial

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[this document]

You may also https://www.youtube.com/watch?v=jAj5AlNr0LE[watch this video] to see the steps in action.

Many steps of the tutorial and video concern the environment setup necessary to undertake the coursework on your own machines. This year much of this setup has been performed for you on university machines.
If you are solely using a university machine to perform the coursework, you should complete only the subsections of the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[tutorial] which are highlighted as necessary for *all students*.

IMPORTANT: Immediately after you create your GitHub account and Red Hat Developers account, email Adam Booth at (a.booth2@ncl.ac.uk) with your name, email address, GitHub username and Red Hat Login ID.
Adam will then create your private repository. You will then receive an email informing you of the details once everything is ready.


== Coursework

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/coursework.asciidoc[this document].

IMPORTANT: You must use the allocation list below to determine which service type you will implement.


== Course Teacher Profiles

*Module (Course) Leader*: *Dr Ellis Solaiman* is the Enterprise Middleware module (course) leader, and also leads a number of courses at the school of Computing Science, Newcastle University including the MSc final Project and Dissertation. He obtained his PhD in Computing Science from Newcastle University in 2004. His research interests are related mainly to the management of distributed systems (Cloud and IoT), trust, and Computer Science Education.

*Industry (Red Hat) Lead:* *Dr Paul Robinson* is a Software Engineering Manager at Red Hat and manages the Engineering team for Red Hat's Developer Program. Prior to this role, Paul was a Principal Software Engineer on JBoss EAP working on the Transaction Manager service. Paul is also a Visiting Fellow at the University. Paul has lead the Enterprise Middleware coursework for over 10 years.

*Head Demonstrator:* *Adam Booth* is a first year PhD student with the Centre for Doctoral Training in Geospatial Systems and is currently researching the application of machine learning and blockchain technologies to geospatial systems. Adam has studied at Newcastle University, undertaking CSC8104 as a postgraduate student. He is currently the head demonstrator on the Enterprise Middleware course.

*Demonstrator:* *Iain Dixon* ...

*Demonstrator:* *Adel Albshri* ...

*Demonstrator:* *Chris Dillon* ...

== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do.

Discussion Boards will also be available for CSC8104 in Blackboard (http://bb.ncl.ac.uk). You may post any questions about the tutorial or coursework assignment here, and the discussion boards will be monitored by Course Demonstrators. Also, any question which demonstrators encounter frequently (either on Blackboard or in practical) will be placed in a *Frequently Asked Questions* document which we maintain https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc[here]. Before asking a question we encourage you to check both these places to see if it has already been answered.

In particular, notice the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc#i-cant-work-out-how-to-do-[answer] which refers to documentation. The use of 3rd party documentation is absolutely *essential* throughout this coursework, and demonstrators may often answer questions by pointing you to the relevant websites.

TIP: If you see a question on the discussion boards you know how to answer, we strongly encourage you to assist your colleagues!


== Allocation List

[options="header"]
|=====
| Student Name | Service Type | Service Location
|Jackson Abraham|Flight|http://apideployment-csc8104-190450621.b9ad.pro-us-east-1.openshiftapps.com
|Kyae S. Chung|Taxi|http://api-deployment-csc8104-160527885.b9ad.pro-us-east-1.openshiftapps.com
|Ziqi Cui|Hotel|
|Jeremy D. Doski|Flight|http://api-deployment-csc8104-190583837.b9ad.pro-us-east-1.openshiftapps.com
|Jmanuel Finelli|Taxi|http://api-deployment-csc8104-190562418.b9ad.pro-us-east-1.openshiftapps.com
|Christos Grigoriadis|Hotel|http://api-deployment-csc8104-160346002.b9ad.pro-us-east-1.openshiftapps.com
|Yuchen Guo|Flight|http://api-deployment-csc8104-190218087.b9ad.pro-us-east-1.openshiftapps.com
|Anastasija Jadrevska|Taxi|http://api-deployment-csc8104-160508666.b9ad.pro-us-east-1.openshiftapps.com
|Runzeng Liu|Hotel|
|Baizel Mathew|Flight|http://api-deployment-csc8104-150143482.b9ad.pro-us-east-1.openshiftapps.com
|Glenn O.J. Mcavoy|Taxi|http://api-deployment-csc8104-160062814.b9ad.pro-us-east-1.openshiftapps.com
|Alexander G. McClelland|Hotel|http://api-deployment-csc8104-190468327.b9ad.pro-us-east-1.openshiftapps.com
|Shiwei Mo|Flight|http://csc8104-build-stream-csc8104-190271244.b9ad.pro-us-east-1.openshiftapps.com
|Alexandros Rantos Charisopoulos|Taxi|http://api-deployment-csc8104-190587101.b9ad.pro-us-east-1.openshiftapps.com
|Mark J. Redman|Hotel|http://csc8104-api-deployment-csc8104-160208238.b9ad.pro-us-east-1.openshiftapps.com
|Martin Robinson|Flight|http://api-deployment-csc8104-150259244.b9ad.pro-us-east-1.openshiftapps.com
|Yuhan Shen|Taxi|http://api-deployment-csc8104-190345626.b9ad.pro-us-east-1.openshiftapps.com
|Joseph D. Straw|Hotel|
|Jinliang Wang|Flight|http://api-deployment-csc8104-190102074.b9ad.pro-us-east-1.openshiftapps.com
|Sebastian Wojtkowiak|Taxi|http://api-deployment-csc8104-150510787.b9ad.pro-us-east-1.openshiftapps.com
|Zhiniu Wu|Hotel|http://api-deployment-csc8104-180682719.b9ad.pro-us-east-1.openshiftapps.com
|Jie Xu|Flight|http://api-deployment-csc8104-190130033.b9ad.pro-us-east-1.openshiftapps.com
|Zhijie Xu|Taxi|http://api-deployment-csc8104-190517902.b9ad.pro-us-east-1.openshiftapps.com
|Chao Zhai|Hotel|http://api-deployment-csc8104-170684048.b9ad.pro-us-east-1.openshiftapps.com
|Jiahan Zhang|Flight|http://api-deployment-csc8104-190515986.b9ad.pro-us-east-1.openshiftapps.com
|Yancheng Zhao|Taxi|http://api-development-csc8104-190346313.b9ad.pro-us-east-1.openshiftapps.com
|Matthew Rodrick|Hotel|http://api-deployment-csc8104-160202203.b9ad.pro-us-east-1.openshiftapps.com
|=======

IMPORTANT: If your name does not appear in the allocation list please contact Adam Cattermole at a.cattermole@newcastle.ac.uk as soon as possible (prior to the first practical session) and you will be assigned a service type and a private GitHub repository.
