= CSC8104 Introduction

The module learning outcomes, and intended skill outcomes can be found on the link:http://www.ncl.ac.uk/undergraduate/modules/csc8104/[Enterprise Middleware page].

To complete this coursework you *MUST* first complete the tutorial document and then move onto the coursework document.

== Tutorial

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[this document]

You may also https://www.youtube.com/watch?v=jAj5AlNr0LE[watch this video] to see the steps in action.

Many steps of the tutorial and video concern the environment setup necessary to undertake the coursework on your own machines. This year much of this setup has been performed for you on university machines.
If you are solely using a university machine to perform the coursework, you should complete only the subsections of the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[tutorial] which are highlighted as necessary for *all students*.

IMPORTANT: Immediately after you create your GitHub account and Red Hat Developers account, email Adam Booth at (a.booth2@ncl.ac.uk) with your name, email address, GitHub username and Red Hat Login ID.
Adam will then create your private repository. You will then receive an email informing you of the details once everything is ready.


== Coursework

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/coursework.asciidoc[this document].

IMPORTANT: You must use the allocation list below to determine which service type you will implement.


== Course Teacher Profiles

*Module (Course) Leader*: *Dr Ellis Solaiman* is the Enterprise Middleware module (course) leader, and also leads a number of courses at the school of Computing Science, Newcastle University including the MSc final Project and Dissertation. He obtained his PhD in Computing Science from Newcastle University in 2004. His research interests are related mainly to the management of distributed systems (Cloud and IoT), trust, and Computer Science Education.

*Industry (Red Hat) Lead:* *Dr Paul Robinson* is a Software Engineering Manager at Red Hat and manages the Engineering team for Red Hat's Developer Program. Prior to this role, Paul was a Principal Software Engineer on JBoss EAP working on the Transaction Manager service. Paul is also a Visiting Fellow at the University. Paul has lead the Enterprise Middleware coursework for over 10 years.

*Head Demonstrator:* *Adam Booth* is a first year PhD student with the Centre for Doctoral Training in Geospatial Systems and is currently researching the application of machine learning and blockchain technologies to geospatial systems. Adam has studied at Newcastle University, undertaking CSC8104 as a postgraduate student. He is currently the head demonstrator on the Enterprise Middleware course.

*Demonstrator:* *Iain Dixon* is a first year PhD student with the Centre for Doctoral Training in Cloud Computing for Big Data. He is currently researching intelligent automated pre-allocation and pre-deallocation of cloud resources. 

*Demonstrator:* *Adel Albshri* is a second-year PhD student in Computer Science at Newcastle University, UK. Adel’s interests lie in the areas of Blockchain, IoT, and Modelling. He earned a Master of Science in Computer and Information Science from Newcastle University, the UK in 2019.

*Demonstrator:* *Chris Dillon* is a first year PhD student in the Secure & Resilient Systems Group and is currently researching the integration of Autonomous Agents with Blockchain Technology. He has an experience with a multitude of technologies and programming languages and has worked as a Professional Software Engineer before returning to higher level academics.

== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do.

Discussion Boards will also be available for CSC8104 in Canvas (http://canvas.ncl.ac.uk) and Teams. You may post any questions about the tutorial or coursework assignment here, and the discussion boards will be monitored by Course Demonstrators. Also, any question which demonstrators encounter frequently (either on Blackboard or in practical) will be placed in a *Frequently Asked Questions* document which we maintain https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc[here]. Before asking a question we encourage you to check both these places to see if it has already been answered.

In particular, notice the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc#i-cant-work-out-how-to-do-[answer] which refers to documentation. The use of 3rd party documentation is absolutely *essential* throughout this coursework, and demonstrators may often answer questions by pointing you to the relevant websites.

TIP: If you see a question on the discussion boards you know how to answer, we strongly encourage you to assist your colleagues!


== Allocation List

[options="header"]
|=====
| Student Name | Service Type | Service Location
| Simileoluwa Aluko |Flight| -
| Bao Chen |Taxi| -
| Yeqin Chen |Hotel| -
| Hao Duan |Flight| -
| Cynthia Sandhanakumar |Taxi| -
| Aayushi Gupta |Hotel| -
| Jacob Hankey |Flight| -
| Haoyuan He |Taxi| -
| Jinjin He |Hotel| -
| Yanpeng Hu |Flight| -
| Shubham Jakhmola |Taxi| -
| Bowen Jin |Hotel| -
| Xiao Jin |Flight| -
| Aswin Veettil |Taxi| -
| Weipeng Kang |Hotel| -
| Sonu Kumar |Flight| -
| Fiona Katharina Lapp |Taxi| -
| Chenjie Li |Hotel| -
| Chongyao Li |Flight| -
| Nan Li |Taxi| -
| Xiaoxia Li |Hotel| -
| Xinkai Li |Flight| -
| Dingkai Liu |Taxi| -
| Shuofei Liu |Hotel| -
| Moulish Mahendiran |Flight| -
| Aidar Mamytov |Taxi| -
| Akshaya Mathur |Hotel| -
| Xueyu Ni |Flight| -
| Muhammad Rosli |Taxi| -
| Baohua Shen |Hotel| -
| Yingying Sheng |Flight| -
| Viktor Soendergaard |Taxi| -
| Haoyu Sun |Hotel| -
| Minghao Tian |Flight| -
| Yaming Wang |Taxi| -
| Igor Wieczorek |Hotel| -
| Boyuan Wu |Flight| -
| Yixiang Xia |Taxi| -
| Jiaxuan Xu |Hotel| -
| Weijun Xue |Flight| -
| Shuning Yang |Taxi| -
| Wei Yu |Hotel| -
| Fanxin Zeng |Flight| -
| Bangyi Zhang |Taxi| -
| Hanyue Zhang |Hotel| -
| Chen Zhou |Flight| -
| Michael Zhou |Taxi| -
| Guofang Zhu |Hotel| -
| Wei Zhu |Flight| -
| David McAlle | Taxi | -
|=======

IMPORTANT: If your name does not appear in the allocation list please contact Adam Booth at a.booth2@newcastle.ac.uk as soon as possible (prior to the first practical session) and you will be assigned a service type and a private GitHub repository.
