= CSC8104 Introduction

The module learning outcomes, and intended skill outcomes can be found on the link:http://www.ncl.ac.uk/undergraduate/modules/csc8104/[Enterprise Middleware page].

To complete this coursework you *MUST* first complete the tutorial document and then move onto the coursework document.

== Tutorial

Follow https://github.com/NewcastleComputingScience/CSC8104-Quarkus-Specification/blob/main/tutorial.asciidoc[this document]

You may also https://www.youtube.com/watch?v=2SkR8hDCpvA[watch this video] to see the steps in action.

Many steps of the tutorial and video concern the environment setup necessary to undertake the coursework on your own machines. This year much of this setup has been performed for you on university machines.
If you are solely using a university machine to perform the coursework, you should complete only the subsections of the https://github.com/NewcastleComputingScience/CSC8104-Quarkus-Specification/blob/main/tutorial.asciidoc[tutorial] which are highlighted as necessary for *all students*.

IMPORTANT: Immediately after you create your GitHub account and Red Hat Developers account, email Adam Booth at (a.booth2@ncl.ac.uk) with your name, email address, GitHub username and Red Hat Login ID.
Adam will then create your private repository. You will then receive an email informing you of the details once everything is ready.


== Coursework

Follow https://github.com/NewcastleComputingScience/CSC8104-Quarkus-Specification/blob/main/coursework.asciidoc[this document].

IMPORTANT: You must use the allocation list below to determine which service type you will implement.


== Course Teacher Profiles

*Module (Course) Leader*: *Dr Ellis Solaiman* is the Enterprise Middleware module (course) leader, and also leads a number of courses at the school of Computing Science, Newcastle University including the MSc final Project and Dissertation. He obtained his PhD in Computing Science from Newcastle University in 2004. His research interests are related mainly to the management of distributed systems (Cloud and IoT), trust, and Computer Science Education.

*Lead Demonstrator:* *Adam Booth* is a third year PhD student with the Centre for Doctoral Training in Geospatial Systems and is currently researching the application of machine learning and blockchain technologies to geospatial systems. Adam has studied at Newcastle University, undertaking CSC8104 as a postgraduate student. He is currently the head demonstrator on the Enterprise Middleware course.

*Demonstrator:* *Adel Albshri* is a final year PhD student in Computer Science at Newcastle University, UK. Adel’s interests lie in the areas of Blockchain, IoT, and Modelling. He earned a Master of Science in Computer and Information Science from Newcastle University, the UK in 2019.

*Demonstrator:* *Kobby Adu-Duodu* is a second year year PhD student at the School of Computing, Newcastle Univeristy. His research interests lie in the development of ontology and Blockchain solutions within Circular Supply Chains. 

*Demonstrator:* *Shamil Al-Ameen* is a PhD student at the School of Computing, Newcastle Univeristy. 

*Industry (Red Hat) Lead:* *Dr Adam Cattermole* is a Software Engineer at Red Hat. Prior to this role, Adam Completed a PhD at Newcastle University School of Computing where he was also lead demonstrator on the Enterprise Middleware module. 

*Industry (Red Hat) Lead:* *Dr Paul Robinson* is a Software Engineering Manager at Red Hat and manages the Engineering team for Red Hat's Developer Program. Prior to this role, Paul was a Principal Software Engineer on JBoss EAP working on the Transaction Manager service. Paul is also a Visiting Fellow at the University. Paul has lead the Enterprise Middleware coursework for over 10 years.

== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do.

Discussion Boards will also be available for CSC8104 in Canvas (http://canvas.ncl.ac.uk) and Teams. You may post any questions about the tutorial or coursework assignment here, and the discussion boards will be monitored by Course Demonstrators. Also, any question which demonstrators encounter frequently (either on Blackboard or in practical) will be placed in a *Frequently Asked Questions* document which we maintain https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc[here]. Before asking a question we encourage you to check both these places to see if it has already been answered.

In particular, notice the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc#i-cant-work-out-how-to-do-[answer] which refers to documentation. The use of 3rd party documentation is absolutely *essential* throughout this coursework, and demonstrators may often answer questions by pointing you to the relevant websites.

TIP: If you see a question on the discussion boards you know how to answer, we strongly encourage you to assist your colleagues!


== Allocation List

[options="header"]
|=====
| Student Name | Service Type | Service Location
| Shakeel M. |Flight| 
| Mayson M.T. Al-Jassim |Taxi| 
| Dinesh Arumugam |Hotel| 
| Kaleem Aziz |Flight|
| Abel T. Babu |Taxi| https://csc-8104-abel-babu-abelthomasbaburedhat-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
| Ajay B. Balasundaram |Hotel| 
| Tenghai Bi |Flight| 
| Matthew Chapman |Taxi| https://csc-8104-matt-chapman-git-matt-chapman52-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
| Youheng Feng |Hotel|
| Mingchun Guan |Flight|
| Haitao He |Taxi| https://csc-8104-haitao-he-git-harry-shat-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/q/swagger-ui/
| Chuanrong Hong |Hotel| 
| Chaojie Hou |Flight| https://csc-8104-chaojie-hou-chaojiehou-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
| Weixuan Huang |Taxi|
| Xiao Jin |Hotel|
| Pratyush Joshi |Flight|
| Muhammed S. Kandakkeel |Taxi|
| Dhruv R. Krishnamachari |Hotel| 
| Amrit Kumar |Flight|
| Diana Kylymnyk |Taxi|
| Yuxian Lai |Hotel|
| Jian Lan |Flight|
| Boyan Li |Taxi| https://csc-8104-boyan-li-git-boyanli-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/q/swagger-ui/
| Xuening Li |Hotel|
| Yuanyuan Li |Flight| 
| Zhuohan Li  |Taxi|
| Chang Liu  |Hotel|https://csc-8104-chang-liu1-lcunique-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
| Jiankai Liu |Flight|
| Pragalbh A. Mandaokar |Taxi| 
| Rajesh V. Muthukrishnan |Hotel|
| Omkar M. Patil |Flight| 
| Adan T. Playil |Taxi|  
| Rahul Rawat |Hotel| https://csc-8104-rahul-rawat-rawatr24-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/
| Ronil Rodrigues |Flight| 
| Prakriti Rout |Taxi| 
| Hisham Salamathullah |Hotel| 
| Ayush Sharma |Flight| 
| Ao Shen |Taxi| http://myroute-shawn-2023-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
| Yuqi Shen |Hotel| https://csc-8104-grover-shen-02-shenyuqi0701-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
| Gursharn K. Soni |Flight| 
| Wei Sun |Taxi| https://csc-8104-eric-sun-a18647904983-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/
| Qi Tong |Hotel|  
| Anushri Vijayendra Kadaramandalagi |Flight| 
| Pan Wang |Taxi| 
| Yifan Wu |Hotel|
| Wei Xie |Flight|
| Zehua Xing |Taxi|
| Xuanhua Yi |Hotel|
| Zhiji Zhan |Flight|  https://csc-8104-zhiji-zhan-zhanzhiji0926-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
| Siming Zhang | Taxi | 
| Guangzhen Zhou |Hotel|
| Zilong Zhou |Flight| 
| Xunxi Zou | Taxi |http://zouxunxi-zouxunxi-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/
|=======


IMPORTANT: If your name does not appear in the allocation list please contact Adam Booth at a.booth2@newcastle.ac.uk as soon as possible (prior to the first practical session) and you will be assigned a service type and a private GitHub repository.
