= CSC8104 Introduction

The module learning outcomes, and intended skill outcomes can be found on the link:http://www.ncl.ac.uk/undergraduate/modules/csc8104/[Enterprise Middleware page].

To complete this coursework you *MUST* first complete the tutorial document and then move onto the coursework document.

== Tutorial

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[this document]

You may also https://youtu.be/X0HlR40DkxI[watch this video], prepared for for last years tutorial, to see the steps in action. It should be noted that there are some minor differences in OpenShift usage this year (Pro instead of Starter), which the video does not reflect.

Many steps of the tutorial and video concern the environment setup necessary to undertake the coursework on your own machines. This year much of this setup has been performed for you on university machines.
If you are solely using a university machine to perform the coursework, you should complete only the subsections of the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/tutorial.asciidoc[tutorial] which are highlighted as necessary for *all students*.

IMPORTANT: Immediately after you create your GitHub account and Red Hat Developers account, email Adam Cattermole at (a.cattermole@ncl.ac.uk) with your name, email address, GitHub username and Red Hat Login ID.
Adam will then create your private repository and grant you access to a project in OpenShift. You will then receive an email informing you of the details once everything is ready.


== Coursework

Follow https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/coursework.asciidoc[this document].

IMPORTANT: You must use the allocation list below to determine which service type you will implement.


== Course Teacher Profiles

*Module (Course) Leader*: *Dr Ellis Solaiman* is the Enterprise Middleware module (course) leader, and also leads a number of courses at the school of Computing Science, Newcastle University including the MSc final Project and Dissertation. He obtained his PhD in Computing Science from Newcastle University in 2004. His research interests are related mainly to the management of distributed systems (Cloud and IoT), trust, and Computer Science Education.

*Industry (Red Hat) Lead:* *Dr Paul Robinson* is a Software Engineering Manager at Red Hat and manages the Engineering team for Red Hat's Developer Program. Prior to this role, Paul was a Principal Software Engineer on JBoss EAP working on the Transaction Manager service. Paul is also a Visiting Fellow at the University. Paul has lead the Enterprise Middleware coursework for over 10 years.

*Head Demonstrator:* *Adam Cattermole* is a second year PhD student with the Centre for Doctoral Training in Cloud Computing for Big Data and is currently researching functional stream processing. Adam has studied at Newcastle University since 2012, undertaking CSC8104 as an undergraduate. He is currently the head demonstrator on the Enterprise Middleware course.

*Demonstrator:* *George Stamatiadis* is a second year PhD student with the Centre for Doctoral Training in Cloud Computing for Big Data and is currently researching crash-tolerant stream processing. George has previously completed a BEng Computer Networks degree at University of Essex.

*Demonstrator:* *Pedro Silva* is a second year PhD student with the Centre for Doctoral Training in Cloud Computing for Big Data. Pedro has a Masters degree in Electrical Engineering from the University of Porto, where he worked as a postgraduate researcher before he joined Newcastle University. His current research interests include distributed algorithms and machine learning applied to intelligent transportation systems.

*Demonstrator:* *Ali Alzubaidi* is a Second Year PhD student who is researching Blockchain technology as potential underlying solution for Service Level Agreement (SLA). He has a Master Degree in Computer Science from Adelaide University (Australia), with a focus on Internet of Things (IoT). He also holds a teaching assistant position at Umm Al-Qura University since 2010.

*Demonstrator:* *Ridwan Suleiman* is a second year PhD student who is researching resource usage prediction in the cloud   with the goal of reducing energy wastage. Ridwan completed his MSC in Software Engineering Management at Durham University.

*Demonstrator:* *Bakri Awaji* is a First Year PhD student who is researching in using Blockchain and Smart Contract to provide an infrastructure for online education. I have received my Master Degree in Computer Science from University of Colorado at Denver (U.S.A). Bakri is a teaching assistant in Computer Science College at Najran University. K.S.A.

== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do.

Discussion Boards will also be available for CSC8104 in Blackboard (http://bb.ncl.ac.uk). You may post any questions about the tutorial or coursework assignment here, and the discussion boards will be monitored by Course Demonstrators. Also, any question which demonstrators encounter frequently (either on Blackboard or in practical) will be placed in a *Frequently Asked Questions* document which we maintain https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc[here]. Before asking a question we encourage you to check both these places to see if it has already been answered.

In particular, notice the https://github.com/NewcastleComputingScience/enterprise-middleware-coursework/blob/master/frequentlyaskedquestions.asciidoc#i-cant-work-out-how-to-do-[answer] which refers to documentation. The use of 3rd party documentation is absolutely *essential* throughout this coursework, and demonstrators may often answer questions by pointing you to the relevant websites.

TIP: If you see a question on the discussion boards you know how to answer, we strongly encourage you to assist your colleagues!


== Allocation List

[options="header"]
|=====
| Student Name | Service Type | Service Location
|Alhawas A.|Taxi|
|Booth A.D.|Flight|
|Chen Y.|Hotel|
|Clark C.|Taxi|
|Dalbehera A.|Flight|
|Dyer P.A.|Hotel|
|He K.|Taxi|
|Jamathi Chidananda P.|Flight|
|Khan A.|Hotel|
|Lei H.|Taxi|
|Li X.|Flight|
|Li Z.|Hotel|
|Liang Y.|Taxi|
|Lin K.|Flight|
|Liu L.|Hotel|
|Sham W.H.|Taxi|
|Shao S.|Flight|
|Tang A.H.W.|Hotel|
|Towers J.A.|Taxi|
|Wang J.|Flight|
|Yang W.|Hotel|
|Zhong S.|Taxi|
|Zhou T.|Flight|
|Zhu R.|Hotel|
|Brown J.K.|Taxi|
|Robertson J.E.|Flight|
|Vydra V.|Hotel|
|=======

IMPORTANT: If your name does not appear in the allocation list please contact Adam Cattermole at a.cattermole@newcastle.ac.uk as soon as possible (prior to the first practical session) and you will be assigned a service type and a private GitHub repository.
