= CSC8104: Enterprise Middleware Tutorial

This tutorial guides you through the necessary preparation required to begin your coursework for this module. It is very important that you have completed this and are comfortable with the example, before the beginning of the first coursework week.

== Create Accounts
To complete this coursework you will need accounts on GitHub and OpenShift.

=== GitHub
GitHub offers the Git version control system as a service. You will use it to host your code and to make it available to the demonstrators. GitHub is very popular in the open-source community and works best when you make your code available to others to view, clone and contribute towards. However, given the confidential nature of your coursework, you will need to use a private repository only accessible by yourself and the demonstrators.

If you don't already have an account you will need to:

1. Go to: https://github.com/
2. Fill in your details and select "Sign up for GitHub."
3. Forward your Github account registration email to Hugo Firth at h.firth@newcastle.ac.uk, including your name and university email address.

If you already have an account, email Hugo Firth at h.firth@newcastle.ac.uk with your name, email address and Github username.

Hugo will then create your private repository and grant you access. You will then receive an email notification from Github containing details of your new repository. This will be sent to the email address you registered with Github.

TIP: GitHub is a very popular service, and you are quite likely to use it in your profesional career; especially if you work with open source software in some capacity.

=== OpenShift
OpenShift is a Platform as a Service (PaaS) Cloud offered by Red Hat. It can host many types of applications, but for this coursework you will be using it to host Java EE 6 applications on JBoss EAP 6.1. OpenShift has a free tier of membership, which you will use for the coursework.

To create an account:

. Go to: https://www.openshift.com
. Select "Signup for Free" under the "Online" option.
. Fill in your details and select "Sign Up".
. You should now receive an email containing a link to confirm your registration.  Click this link and confirm that you agree to OpenShift's terms of use.

== Environment Setup

Once you have confirmed (as mentioned above) your email address with OpenShift, you will be directed to a web page titled https://www.openshift.com/get-started["Get Started"]. On this page you will need to select the *Command Line* option at the top of the page and follow the first two steps of the instructions subsequently listed. Once you have completed these steps you should have successfully created an OpenShift account, installed Ruby and the Openshift RHC Client Tools on your computer.

* *Setup*. When running the `rhc setup` command you will be asked for your openshift *login* and *password*. Your login details are those used to register for OpenShift. When asked to provide a namespace for your projects, you should provide your student number (e.g 100826753).

IMPORTANT: If you encounter an "Access is denied" warning when running the RubyInstaller setup program, you should copy the installer into C:/temp, right click the executable and select "Run as Administrator". You will be prompted for your admin password for your machine, and Ruby should then install successfully.

IMPORTANT: If you encounter a "Permission denied" warning when installing the rhc gem, you should run the Command Prompt as an administrator (right click the shortcut and select "Run As Administrator") and retry. You will be prompted for your admin password for your machine, and the rhc gem should then install successfully.

== Run Example
Now you will run a simple example. This example provides you with a starting point that you will build on when you come to doing the coursework. Therefore, it is very important that you get this working and become familiar with the code.

=== Download JBoss EAP 6.2.0
1. Go here: http://www.jboss.org/products/eap/download/.
2. Click "View Older Downloads"
3. Download the zip distribution of JBoss EAP 6.2.0.GA. _Note:_ You need to make sure you use this version of JBoss EAP as this matches the version you will be using on OpenShift. You will be required to register for the https://community.jboss.org/[JBoss community] website as part of the download process.
4. Unzip JBoss EAP to somewhere on your computer.

=== Obtain the kitchensink-angularjs Quickstart

1. Visit the KitchenSink-AngularJS quickstart page http://www.jboss.org//quickstarts/wfk/kitchensink-angularjs/index.html[here].

2. CLick on the `Download` link to obtain all the Quickstarts
3. Unzip the download to somewher eon your computer.
4. Open a terminal and go to the `kitchensink-angularjs` directory in the quickstart bundle you just unzipped.


=== Run the Quickstart
1. Step through the instructions on the KitchenSink-AngularJS quickstart page, upto and including section "Run the Arquillian Functional Tests". Make sure you follow the "Configure Maven" section correctly as these instructions are important.
2. Now follow the section "Build and Deploy the Quickstart to OpenShift" including all the sub-sections that take you to the end of the page.


== Eclipse Setup
If you want to use Eclipse to edit the kitchensink-angularjs example (and your coursework), you must follow these steps:

. *Install m2eclipse*. Google "Install m2eclipse <your Eclipse version>". Note: the procedure differs between eclipse versions
. *Import the maven project into eclipse*.
  .. Within a new workspace, click 'File' -> 'Import...'
  .. Select 'Maven' -> 'Existing Maven Projects'
  .. Click on 'Browse' and select the quickstart you wish to import.
  .. Click 'Finish'

== Working with Git
You will be using Git in the coursework for regular checkpoint and backup of your code to GitHub. You will also use Git to deploy new versions of your application to OpenShift. This section will show you how to create a copy of the 'kitchensik-angularjs' example, ready fo you to extend in the coursework, and also how to push the code to GitHub and OpenShift.

* Build on top of the kitchensink-angularjs example, by moving your clone of the OpenShift git repository at kitchensink-angularjs/kitchensinkangularjs to some other location on your disk, where you want to develop your coursework submission.
* Now you need to be able to push your code to your git repository on GitHub. To do this, you will need the url of the repository created by Hugo on your earlier request.

    git remote add github https://github.com/NewcastleComputingScience/csc8104-<YOUR ID>.git
    git push github master -f

WARNING: The -f flag for git push should not be used after this initial setup. Doing so may result in the loss of commits in the remote repository.

* When you work with Git there are often files you wish for Git to ignore and exclude from your repository. These may include confidential data or files generated by your IDE. This is achieved using a .gitignore file which specifies the files and/or directories you wish to exclude. We suggest you use the .gitignore file provided in this csc8104-assignment repository. Copy this file into your repository and commit the file using the following commands.

   git add .gitignore
   git commit -m 'Adding .gitignore file.'

TIP: If you are new to Git, you should read Pro Git.  Chapters 1-3 should cover all the functionality required for this coursework.  Available at: http://git-scm.com/book

== Viewing your datasource
During development of your application you may find it very useful to be able to inspect the contents of your database. To do this you will use h2console, which is provided as part of the quickstarts.

=== Deploying h2console

Obtain the `h2console.war` file from here: https://github.com/jboss-developer/jboss-eap-quickstarts/tree/master/h2-console and copy it into the "deployments" directory of your repository.

Add this file to your git repository, commit and push.

    git add deployments/h2console.war
    git commit -m 'h2console.war first commit'
    git push

=== Accessing h2console
You can access the console at http://<yourdomainname>.rhcloud.com/h2console.

To log into the datasource for your application, use the following details.

    Driver Class: javax.naming.InitialContext
    JDBC URL: Your JDBC URL is available in your persistence.xml file, and can be found between the <jta-data-source> tags e.g. java:jboss/datasources/KitchensinkAngularJSQuickstartDS
    Username: sa
    Passowrd: sa

. Click "Test Connection" and if these details are correct you will see "Test successful".

. Press "Connect" to view the contents of the datasource.

TIP: Your persistence.xml is the configuration file used to specify the connection details to your database. Your persistence.xml file can be found in src/main/resources/META-INF.

== Testing your API

Besides the Arquillian tests run through maven, you will occasionally want to test your API in a more manual fashion, in order to clearly see what information is being sent and received.

One common method for sending network requests from the command line is a tool called link:http://curl.haxx.se/[cURL].

cURL should already be installed on your machines, if it is not, please contact Hugo Firth (h.firth@ncl.ac.uk) as soon as possible.

To give you an example of how you might use cURL to see what your API is doing, once the QuickStart is running (either locally or on OpenShift) you could execute the following commands (in cmd.exe):

* to see a list of all members returned, formatted as JSON and accompanied by all HTTP headers.

    curl -v http://localhost:8080/members/

* to create a new member.

    curl -v -X POST http://localhost:8080/members/ -d '{"name":"Joe Bloggs", "phonenumber":"01234567891"}'

The *-v* switch instructs curl to display all possible information, whilst the *-X* switch allows you to specify the HTTP method to be used and *-d* the data to be sent.

TIP: If you would like to learn more about how to use cURL, you can refer to the link:http://curl.haxx.se/docs/manpage.html[official documentation] or link:http://code.tutsplus.com/tutorials/a-beginners-guide-to-http-and-rest--net-16340[this] useful tutorial.

== Course Demonstrator Profiles

*Dr Paul Robinson* is a Senior Software Engineer at Red Hat and a Visiting Research Fellow at the University. Paul develops software for the JBoss application server and in particular for the Transaction Service component. Paul has lead the Enterprise Distributed Computing coursework for 9 years. He also supervises students for their Masters dissertation through industrial placements at Red Hat.

*Matt Forshaw* is a fourth year PhD student at Newcastle University. After completing his BSc and MSc ITEC (with Distinction) at Newcastle University, Matt has demonstrated and assessed on CSC8104 for the past four years. Matt is a member of the Systems research group investigating energy efficient operating policies for large computing environments. He also supervises student research projects and dissertations in the areas of energy-efficiency and green computing.

*Becky Simmonds* is a third year PhD student researching into Twitter analysis using online and offline techniques. She demonstrated on CSC8104 the last two years and completed it herself the year before. Becky demonstrates on other modules and helps supervise a final year dissertation.

*Ryan Emerson* is a third year PhD student who has studied at Newcastle University since 2007. Ryan graduated with a 2:1 BSc (Hons) in Computer Science in 2010 and obtained his Masters (ITEC) with Distinction in 2011. Currently Ryan is part of the Systems research group conducting research into probabilistic atomic broadcast protocols.

*Hugo Firth* is a first year PhD student with the Systems research group. Studying at Newcastle University since 2010, Hugo graduated with a BSc in Computer Science (1st Class) earlier this year. Since 2009 Hugo has offered freelance development services, providing API-centric web development to clients ranging from Web hosts to Game developers; he has recently completed a number of projects using AngularJS.


== Finally
Demonstrators will be available in your cluster rooms during all practical sessions. You should go and see them if you are having any difficulties. This includes understanding what you have to do.

Discussion Boards will also be available for CSC8104 in Blackboard (http://bb.ncl.ac.uk). You may post any questions about the tutorial or coursework assignment here, and the discussion boards will be monitored by Course Demonstrators. Before posting you should use the discussion boards' search facilities to see if somebody has already encountered the same problem.

TIP: If you see a question on the discussion boards you know how to answer, we strongly encourage you to assist your colleagues!


== Allocation List

[options="header"]
|=====
| Student name | Student number | Service
|=====

IMPORTANT: If your name does not appear in the allocation list please contact Hugo Firth at h.firth@ncl.ac.uk as soon as possible (prior to the first practical session) and you will be assigned a service type and a private GitHub repository.
